# Generated by Django 2.2 on 2019-10-10 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('investments', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('bills', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('leisure', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('mortgage', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('documents', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicroLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_status', models.BooleanField()),
                ('creditor_status', models.BooleanField()),
                ('interest', models.SmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration', models.SmallIntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2, verbose_name='status')),
                ('borrower', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower', to='userinfo.UserInfo')),
                ('creditor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditor', to='userinfo.UserInfo')),
            ],
        ),
    ]
